server:
  port: 9000


##
# MySQL Data Source Configuration
##
spring:
  datasource:
     url: jdbc:mysql://localhost:3306/db_mifos_payment_bridge?useSSL=true
     username: root
     password: mysql
     driver-class-name: com.mysql.jdbc.Driver
 # Keep the connection alive if idle for a long time (needed in production)
     tomcat:
       testWhileIdle: true
       validationQuery: SELECT 1

# ===========================================================================================
# = JPA / HIBERNATE
# ===========================================================================================
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      
      
# ===========================================================================================
# = Mifos config
# ===========================================================================================
mifos:
  baseUrl: https://localhost:8443/fineract-provider/api/v1/
  username: mifos
  password: password
  